### ISSUE TITLE
Add sounds to be played with haptics

### ISSUE THREAD

**Issue by jbphet** [phetsims/tappi#10]
In today's sound design meeting (11/9/2021) a very early prototype of the "Haptics Playground" was demonstrated.  It was suggested that the code also play sounds to go along with the haptics so that users can at least get some idea of what should be happening when testing on devices that have no haptics capability.  We are thinking that the sound should be something that creates a sense of vibration, kind of like the ringback tone that is heard here in the US.

We are also thinking that having a very bass-heavy sound might be able to create an illusion of haptics by vibrating the device on which it is being played.

@ashton agreed to create two new sounds that could work for this, one a basic, warbly sort of sound, and another that is similar but includes a lot of bass to try to vibrate the device.

**Comment by Ashton-Morris** [comment]
I have some some sounds to try out. [Link](https://drive.google.com/drive/folders/1MvoFmyoQidly_EzJKfLNSCrA-_S88-JN?usp=sharing)


- haptic-buzz-loop.mp3
- haptic-buzz-loop.wav
- haptic-buzz-loop-with-bass.mp3
- haptic-buzz-loop-with-bass.wav

**Comment by jbphet** [comment]
Sounds have been added, I think it's safe to close this.

**Comment by jbphet** [comment]
Wait, actually, I think we said there should be an AB switch for the sound, or at least a checkbox.  I should implement that before closing this.

**Comment by jbphet** [comment]
I've added a checkbox, which should probably do it for now.  I'll review with the design team today.

**Comment by jbphet** [comment]
The sound design team discussed this in today's meeting, and we decided that this can be closed.  If we want to add more sophisticated sound later, we'll do that under new issues.
