### ISSUE TITLE
Vibration manager loading on non-iOS device witout a request to do so

### ISSUE THREAD

**Issue by terracoda** [phetsims/tappi#15]
For some strange reason I am getting an error about the Vibration Manager on my Macbook Pro MacOS 12.2.1 in the Safari browser. I haven't test other browsers.

Discussed with @jessegreenberg 

Here's a screen of what we tried:
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/1902116/176500737-ccd2153d-e035-4f9f-9d3a-ac4b86e5216f.png">
Close-up of error message:
<img width="501" alt="image" src="https://user-images.githubusercontent.com/1902116/176500951-e2f9caa0-173b-445f-b781-e2711197de1c.png">

Here's the URL which has no query parameter:
https://bayes.colorado.edu/dev/phettest/gravity-force-lab-basics/gravity-force-lab-basics_en.html?ea&brand=phet

We tried clearing caches loading from PhET Marks and from the general phettest page - both loads had the same issue.

**Comment by terracoda** [comment]
We also tested John Travoltage. That sim loaded fine.

**Comment by jessegreenberg** [comment]
I was able to confirm the problem on my macOS 11.6.2 on safari thorugh phettest. I will try to get it to happen locally on this same machine to debug and find how we are calling this without the `?vibrationParadigm` query param.

**Comment by jessegreenberg** [comment]
Ah, I found it. This is a continuatoin of https://github.com/phetsims/tappi/issues/14. We cannot use platform specific things outside of constructors and one currently lives in VIbrationPatterns.ts:

```
if ( platform.safari ) {
  vibrationManagerInstance = new VibrationManageriOS();
}
else {
  vibrationManagerInstance = {
    vibrateTransient( options?: VibrateOptions ) {
      console.warn( 'vibrateTransient called on non-iOS platform' );
    }
  };
}
```

**Comment by jessegreenberg** [comment]
Closing to continue in #14.
